name       : libisofs
version    : 1.5.6
release    : 6
source     :
    - https://files.libburnia-project.org/releases/libisofs-1.5.6.tar.gz : 0152d66a9d340b659fe9c880eb9190f3570fb477ac07cf52e8bcd134a1d30d70
homepage   : https://dev.lovelyhq.com/libburnia/libisofs
license    : GPL-2.0-or-later
component  : programming.library
summary    : libisofs is a library to create an ISO-9660 filesystem with extensions like RockRidge or Joliet
description: |
    libisofs is a library to create an ISO-9660 filesystem with extensions like RockRidge or Joliet. It is also a full featured ISO-9660 editor, allowing you to modify an ISO image or multisession disc, including file addition/removal, change of file names and attributes, etc.
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
