name       : libisofs
version    : 1.4.6
release    : 4
source     :
    - http://files.libburnia-project.org/releases/libisofs-1.4.6.tar.gz : 14ab0b384e988d651092ca184d5f18dba83a9cfa05ff5e581770d6baa879a50a
license    : GPL-2.0
component  : programming.library
summary    : libisofs is a library to create an ISO-9660 filesystem with extensions like RockRidge or Joliet
description: |
    libisofs is a library to create an ISO-9660 filesystem with extensions like RockRidge or Joliet. It is also a full featured ISO-9660 editor, allowing you to modify an ISO image or multisession disc, including file addition/removal, change of file names and attributes, etc.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
